sudo: required
language: python
python:
  - "2.7"
  - "3.5"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y pigz
install: pip install tox-travis flake8
script:
  - tox
  - flake8
